### ISSUE TITLE
Feature Request: Sorted Plist parameters

### ISSUE THREAD

**Issue by ekscrypto** [Harley-xk/AssetsProcessor#2]
When generating the PLIST, is there any way to ensure that the parameters are always ordered the same?  Otherwise we keep getting file diff that looks like this when re-processing the xcassets:
<img width="2032" alt="screenshot 2017-07-04 07 37 20" src="https://user-images.githubusercontent.com/472733/27828744-d9e1ea34-608b-11e7-9714-9cb311a85f86.png">

**Comment by Harley-xk** [comment]
Thanks for your support！
This issue is resolved in the latest version 1.0.1
